### PR TITLE
Update ragavi

### PR DESCRIPTION
**Pull request by Mulan-94**
- Change `ragavi` tag to 1.7.3
- Delete `--gaintype` from `ragavi` cab
- Change `--k-xaxis` to `--xaxis` in `ragavi` cab

### CODE REVIEW

**Comment by paoloserra** [comment]
@SpheMakh @molnard89 can you please coordinate work to review and merge this? We'd really like to have the nice ragavi plots back on ILIFU!

**Review by o-smirnov — APPROVED** [review]

**Comment by o-smirnov** [comment]
OK @Mulan-94 approved, but one question: the ``gaintype`` argument has been dropped (presumably because you auto-detect now?), but I see that a couple of caracal workers are still using it. This means that the next Stimela release is going to break Caracal master. Don't we need a corresponding PR in Caracal to fix this?

**Comment by o-smirnov** [comment]
ok to test

**Comment by o-smirnov** [comment]
retest this please

**Comment by o-smirnov** [comment]
This sort of change is the sort of stuff that @gigjozsa was always worried about. As things stand, pushing out a release of Stimela with this PR in will break Caracal's assumed compatibility with the latest Stimela release. We'd have to merge https://github.com/caracal-pipeline/caracal/pull/1249 and release an update of Caracal for things to keep working.

In general, this is almost inevitable as we evolve our packages, but we can try to avoid pain as much as possible by restricting breaking API changes within point releases. So in this particular case, @Mulan-94, do I understand correctly that ``gaintype`` is now auto-detected, so the parameter is no longer necessary? If that is the case, then I think it would be better to:

* leave the parameter in for now

* print a warning if the parameter is passed: "The gaintype parameter is deprecated and will be removed in a future release"

* double-check that nothing breaks (for now) with Caracal continuing to pass in the now-ignored ``gaintype``

* deprecate it in Stimela 1.8 or 2 or whatever.

**Review by o-smirnov — CHANGES_REQUESTED** [review]
See comment on gaintype.

**Comment by o-smirnov** [comment]
Likewise for ``k-axis``, can't we warn it is deprecated, but treat it as an alias for xaxis?

**Comment by Mulan-94** [comment]
Ok @o-smirnov I've returned those arguments here and in `ragavi` as well for compatibility

**Comment by o-smirnov** [comment]
Thanks! Does it print a deprecation warning?

I'm wondering if I should just add an optional ``deprecated: true`` field to ``parameters.json``. Then Stimela can issue a warning centrally if it sees a cab invoked with a deprecated parameter. We're bound to run into this situation again, so why not address it centrally?

**Comment by Mulan-94** [comment]
No I've just put the warning in it's description. I think the deprecated field is a good idea.

**Comment by o-smirnov** [comment]
OK @Mulan-94 I pushed a change that should print a deprecation warning, please check that this indeed happens.

So ragavi-gains itself is updated to keep on recognizing the deprecated arguments for the time being?

**Comment by Mulan-94** [comment]
> So ragavi-gains itself is updated to keep on recognizing the deprecated arguments for the time being?

Yeah

> please check that this indeed happens.

On this

**Comment by o-smirnov** [comment]
retest this please

**Review by o-smirnov — APPROVED** [review]

**Pull request merged**
