### PR TITLE
cubical 1.5.8 release

### PR DESCRIPTION
**Pull request by o-smirnov**
The previous cubical base image was tagged 1.6.7. I'm sorry, I tried to make an image tagged 1.6.8 containing CubiCal release 1.5.8, but a little OCD homunculus inside me woke up, stomped its feet and shouted, "No more! Cannot take! Consistent versions matter!"

So I gave in, and tagged the new image 1.5.8. If there's a secret user community out there using vintage 1.5.8 images (containing CubiCal release 1.3.6, no doubt...), they've just been royally and callously screwed. Sorrynotsorry.

Seriously though, may I suggest we slowly gravitate to a situation where Stimela image tags follow the underlying package version (at least for "single malt" cabs such as e.g. cubical and wsclean)? This may mean revising some tags "down", as is the case here, but that's ok, right?

### CODE REVIEW

**Comment by o-smirnov** [comment]
P.S. I uploaded the image to quay.io. In the interregnum, I probably need to upload to docker.io too, right?

**Comment by gigjozsa** [comment]
As a freshman with his first cab just submitted I'd upvote the suggestion of Oleg's. The great benefit would be that two different images would not be tagged with the same tag twice (depending of the morale of the tagger, of course). That would be really great for the user (which I have been for a long time now).

**Review by SpheMakh — APPROVED** [review]
Looks good

**Comment by bennahugo** [comment]
I'm not so sure I support the suggestion. I prefer the upload only as
needed policy where the image version numbers only increase when the image
actually changes. Otherwise there is a lot of very expensive duplication of
singularity images.

Can you perhaps roll back the image to that of the previous commit Oleg?

**Comment by bennahugo** [comment]
It is perhaps better to keep a central manifest with the current version
numbers which we can bump as needed along with a centralized image build
command so that this process is not manual. It can check if the image tag
exist (via a request json to the hub) and only push if the version tag does
not exist.

**Comment by o-smirnov** [comment]
Yep, that's exactly the point of #692. On it already.

**Pull request merged**
