### PR TITLE
Update cubical 150

### PR DESCRIPTION
**Pull request by bennahugo**
Lets **PLEASE** wait for the tests to pass. I want to get a cubical test in here but it may take some fine tuning to keep it in the memory budget

### CODE REVIEW

**Comment by bennahugo** [comment]
Btw. Master is now broken because it wasn't checked whether the test passes or not

**Comment by SpheMakh** [comment]
cubical issues has been fixed in release 1.5.1. see PR #579 

You can close this

**Comment by bennahugo** [comment]
retest this please

**Comment by bennahugo** [comment]
retest this please

**Pull request closed without merging**
