### PR TITLE
add description of sofia parameters

### PR DESCRIPTION
**Pull request by paoloserra**

### CODE REVIEW

**Comment by KshitijT** [comment]
@paoloserra , could you please sync with the master branch?

**Comment by paoloserra** [comment]
done

**Comment by SpheMakh** [comment]
ok to test

**Comment by SpheMakh** [comment]
@paoloserra has the SoFia release been made yet?

**Comment by paoloserra** [comment]
> @paoloserra has the SoFia release been made yet?

yes, you should  check slack! :)

there'll be a few new parameters, so maybe make it a separate PR?

**Comment by SpheMakh** [comment]
I will push a new image, and you can modify the cab in this PR.

**Pull request merged**
