### PR TITLE
remove scabha from wsclean cab (For now)

### LINKED ISSUE #650: multiscale-scales does not work any more
Something seems to be wrong with the new master / release version of stimela. I used to set multiscale-scales as:

`      "multiscale-scales": [0,10,20,40,80,160,320,400],
`
However, running the same script after a stimela update gives an error:

```
# 2020-06-21 17:05:42: Running wsclean -name /stimela_mount/output/circinus-full-2-flagged-briggs_0.0_fullmask2_small -j 32 -mem 100 -no-update-model-required -weight briggs 0.0 -size 500 500 -scale 1.3arcsec -channels-out 32 -no-small-inversion -pol I -data-column CORRECTED_DATA -niter 3000000 -auto-threshold 0.001 -auto-mask 5 -gain 0.1 -mgain 0.9 -join-channels -multiscale -multiscale-scales 0 10 20 40 80 160 320 400 -fit-spectral-pol 2 -deconvolution-channels 4 -nmiter 20 /stimela_mount/msdir/1532022061_8s-circinus_p3_corr.ms
# 
# WSClean version 2.9.0 (2020-03-27)
# This software package is released under the GPL version 3.
# Author: André Offringa (offringa@gmail.com).
# 
# + + + + + + + + + + + + + + + + + + +
# + An exception occured:
# + >>> Table /stimela_mount/output/10 does not exist
# + + + + + + + + + + + + + + + + + + +
# 2020-06-21 17:05:43: wsclean exited with code 255
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR: docker returns error code 1
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR: job failed at 2020-06-21 17:05:43.446906 after 0:00:01.796875
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR: Traceback (most recent call last):
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR:   File "/data2/kshitij/Stimela/stimela/recipe.py", line 693, in run
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR:     job.run_job()
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR:   File "/data2/kshitij/Stimela/stimela/recipe.py", line 423, in run_job
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR:     self.job.start(output_wrangler=self.apply_output_wranglers)
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR:   File "/data2/kshitij/Stimela/stimela/docker.py", line 171, in start
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR:     kill_callback=lambda: utils.xrun("docker", ["kill", self.name]))
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR:   File "/data2/kshitij/Stimela/stimela/utils/xrun_poll.py", line 189, in xrun
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR:     raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
2020-06-21 17:05:43 STIMELA.image_3_briggs_0_fullmask2_small ERROR: stimela.utils.StimelaCabRuntimeError: docker returns error code 1
2020-06-21 17:05:43 STIMELA.Image circinus broadband INFO: Completed jobs : []
2020-06-21 17:05:43 STIMELA.Image circinus broadband INFO: Remaining jobs : []
2020-06-21 17:05:43 STIMELA.Image circinus broadband INFO: Saving pipeline information in .last_Image_circinus_broadband.json
Traceback (most recent call last):
  File "/data2/kshitij/docker_shm_venv/bin/stimela", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/data2/kshitij/Stimela/bin/stimela", line 14, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/data2/kshitij/Stimela/stimela/main.py", line 602, in main
    _cmd(argv)
  File "/data2/kshitij/Stimela/stimela/main.py", line 216, in run
    exec(stdr.read(), _globals)
  File "<string>", line 877, in <module>
  File "/data2/kshitij/Stimela/stimela/recipe.py", line 744, in run
    raise PipelineException(exc, self.completed, job, self.remaining) from None
stimela.exceptions.PipelineException: Job 'image_3_briggs_0_fullmask2_small::Image' failed: docker returns error code 1
```

Runs fine if I don't specify multiscale-scales. 

If the format has changed, please update the documentation.

### PR DESCRIPTION
**Pull request by SpheMakh**
Fixes #650

### CODE REVIEW

**Comment by o-smirnov** [comment]
So what was broken?

**Comment by KshitijT** [comment]
Multiscale.

**Comment by o-smirnov** [comment]
Well if it's just the argument parsing, then let's fix it...

**Comment by SpheMakh** [comment]
> Well if it's just the argument parsing, then let's fix it...

There may be other things I missed, I'm working on a more comprehensive fix. But for now, it's easier to rollback

**Comment by o-smirnov** [comment]
OK, let me know if I can help.

**Comment by KshitijT** [comment]
Great, let me test this out - it was holding back one of my reductions.

**Comment by KshitijT** [comment]
Seems like goes through with multiscale-scales now. Of course, the output on the wsclean command is now truncated, but this is just a patch, so I guess fine for now..

**Comment by KshitijT** [comment]
Spoke too soon.
I get a new error now:
```
# Cleaning up temporary files...
# + + + + + + + + + + + + + + + + + + +
# + An exception occured:
# + >>> Error opening temporary data file
# + + + + + + + + + + + + + + + + + + +
# Traceback (most recent call last):
#   File "/stimela_mount/code/run.py", line 63, in <module>
#     subprocess.check_call(shlex.split(_runc))
#   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
#     raise CalledProcessError(retcode, cmd)
# subprocess.CalledProcessError: Command '['wsclean', '-name', '/stimela_mount/output/circinus-full-2-flagged-briggs_0.0_fullmask2_small', '-j', '32', '-mem', '100', '-no-update-model-required', '-weight', 'briggs', '1.0', '-size', '5000', '5000', '-scale', '1.3arcsec', '-channels-out', '32', '-no-small-inversion', '-pol', 'I', '-data-column', 'CORRECTED_DATA', '-niter', '3000000', '-auto-threshold', '0.001', '-auto-mask', '5', '-gain', '0.1', '-mgain', '0.9', '-join-channels', '-multiscale', '-multiscale-scales', '0,10,20,40,80,160,320,400', '-fit-spectral-pol', '2', '-deconvolution-channels', '4', '-nmiter', '20', '/stimela_mount/msdir/1532022061_8s-circinus_p3_corr.ms']' returned non-zero exit status 255.
```

Any idea why?

**Comment by o-smirnov** [comment]
> Any idea why?

AFAIK, wsclean likes to write the visibilities to a temp file in the current working directory. So @SpheMakh you might need to make sure you chdir to the output dir before running it.

**Comment by SpheMakh** [comment]
It is already executed from a writable temporary directory. Also, wsclean uses the directory with the MS to create temp files
```
-temp-dir <directory>
Set the temporary directory used when reordering files. Default: same directory as input measurement set.
```

Did you maybe delete the temp files by mistake while wsclean was running, or is your `msdir` read-only for some reason?

**Comment by KshitijT** [comment]
>Did you maybe delete the temp files by mistake while wsclean was running, or is your msdir read-only for some reason?

No and no. The same script has been run successfully before. Maybe someone else can test this out?

**Comment by SpheMakh** [comment]
Could you please delete the temp files in `msdir` then try again. 

```
rm  msdir/*.tmp
```

**Comment by SpheMakh** [comment]
I've tested this many times now, and different machines. I cannot reproduce this. @KshitijT  please point me to the MS and the wsclean options you parse

**Comment by KshitijT** [comment]
> I've tested this many times now, and different machines. I cannot reproduce this. @KshitijT please point me to the MS and the wsclean options you parse

My apologies - I wanted to be very sure that this works, rather than triggering a false go-ahead. I should have tested it out with a small dataset, instead I went ahead with the full dataset, so took some time to confirm. 
In short, yes, removing the .tmp files works, multiscale is working again.

Thanks, @SpheMakh .

**Comment by o-smirnov** [comment]
Could we **please please** add a quick hack to echo the wsclean command to the console. Scabha would have done this automatically, so if it's not being used at the moment, then we need that kludge.

I'm seeing some terrible images coming out of the wsclean step in the selfcal worker. Basically looks like it barely cleans anything. Things **seem** to work a bit better if I just run wsclean by hand outside the pipeline. But without knowing the wsclean command that ejnds up being used, I'm flying blind trying to diagnose this.

**Comment by SpheMakh** [comment]
shit, I thought I had done this.

**Comment by KshitijT** [comment]
Erm, we really need this - I can't verify that the parameters (like absmem) I am adding to CARACal are actually working.

**Pull request merged**
