### PR TITLE
Base cubical off DDF 0.5 for degridding support

### PR DESCRIPTION
**Pull request by bennahugo**
Add degridding support in cubical. Testing through vermeerkat in progress.

### CODE REVIEW

**Comment by KshitijT** [comment]
> Looks hood

Robin, of Nottingham?

**Comment by bennahugo** [comment]
I'm still running actual tests as part of pipelining this, but both cubical and ddfacet imports correctly in building so I don't see that there is anything wrong with the image.

**Comment by bennahugo** [comment]
Ok one of the C++ library names have changed in DDF >0.5 and it needs a change in cubical. I will need to base off 0.4.1 instead - not that any of the core functionality is different

**Comment by bennahugo** [comment]
Please revert this it isn't working yet

**Pull request merged**
