### PR TITLE
Fixes caracal/1150

### LINKED ISSUE #632: stimela pull seems to ignore STIMELA_PULLFOLDER
STIMELA _PULLFOLDER is only referenced in recipe.py, which means stimela pull does not use it.

SINGULARITY_PULLFOLDER is used by (some?) versions of singularity by default. (Confusingly, this is also mentioned in a docstring in Stimela.) So I guess ``stimela pull`` ends up pulling into that, if set.

To avoid confusion, I think both ``stimela pull`` and ``recipe.py`` should use STIMELA_PULLFOLDER if set.

### PR DESCRIPTION
**Pull request by SpheMakh**
Fixes #632

### CODE REVIEW

**Comment by SpheMakh** [comment]
retest this please

**Comment by SpheMakh** [comment]
retest this please

**Comment by gigjozsa** [comment]
I tested this, it works with Singularity 3.5, but not yet with Singularity 2.6 . Nevertheless this is an important improvement, so I request a release.

**Comment by SpheMakh** [comment]
I'll have a stab at fixing the 2.6.0 error before I push out a release. Give me a few hours

**Comment by gigjozsa** [comment]
OK, thanks for finding out what's going on!

**Pull request merged**
