### PR TITLE
Ragavi

### PR DESCRIPTION
**Pull request by SpheMakh**

### CODE REVIEW

**Comment by o-smirnov** [comment]
@KshitijT can you test if this branch works for you on com08 now.

**Comment by KshitijT** [comment]
Two questions:

1. Shall I retest on Com08 after 0543b54 ?
2. What is garavi ?

**Comment by SpheMakh** [comment]
@KshitijT, yes please

**Comment by KshitijT** [comment]
> @KshitijT, yes please

Testing.

**Comment by SpheMakh** [comment]
We just need `listobs` to go through

**Comment by KshitijT** [comment]
> We just need `listobs` to go through

Listobs went through as of 0543b54  on docker, see conversation on slack. Ragavi-vis was another matter..

**Pull request merged**
