### PR TITLE
Cubical ddf

### LINKED ISSUE #606: singularity imports ${HOME} inside the container and causes version clashes
This is again broken in singularity. Singularity ignores paths set up in the docker container so scipy has to be removed from the base
```
#   File "/usr/local/lib/python3.6/dist-packages/cubical/degridder/DicoSourceProvider.py", line 3, in <module>
#     from DDFacet.Imager import ModModelMachine as MMM
#   File "/usr/local/lib/python3.6/dist-packages/DDFacet/__init__.py", line 23, in <module>
#     __version__ = pkg_resources.require("DDFacet")[0].version
#   File "/home/hugo/vmk_test/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
#     needed = self.resolve(parse_requirements(requirements))
#   File "/home/hugo/vmk_test/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
#     raise VersionConflict(dist, req).with_context(dependent_req)
# pkg_resources.ContextualVersionConflict: (scipy 1.4.1 (/home/hugo/vmk_test/venv3/lib/python3.6/site-packages), Requirement.parse('scipy<=1.3.3'), {'DDFacet'})
```

### PR DESCRIPTION
**Pull request by SpheMakh**
Avoids host settings from leaking into the container. Fixes #606

### CODE REVIEW

**Comment by bennahugo** [comment]
Lets test whether this works. Explicitly calling /usr/bin/python is not a good idea, because
By default ubuntu ships Python 2.7. This explicitly invokes that version of python. A whole bunch of software no longer supports this version.

**Comment by bennahugo** [comment]
why don't you call ```$(which python) ....```

**Comment by SpheMakh** [comment]
> why don't you call $(which python) .... 

Yes this is more robust

**Comment by o-smirnov** [comment]
Why not ``/usr/bin/python3`` then? *Not* using an explicit path to the interpreter is part of what got us into this mess to begin with. And if you're shipping images, you know exactly where the interpreter should be (and if it isn't there, then that's an error we're better off reporting immediately!)

**Comment by bennahugo** [comment]
some software is still python 2.7

**Comment by SpheMakh** [comment]
> remove which python and add
> 
> ```
> xvfb-run -a $(which python) $STIMELA_MOUNT/code/run.py 2>&1
> ```

Done

**Comment by SpheMakh** [comment]
Will merge when this test passes

**Comment by SpheMakh** [comment]
[not good](https://media.giphy.com/media/NmMb69LluiCmA/giphy.gif)!

`Data-ColName` really!?

**Comment by KshitijT** [comment]
> not good
> 
> `Data-ColName` really!?

What are you talking about?

**Comment by SpheMakh** [comment]
> What are you talking about? 

Screenshot from 2020-05-12 15-16-43

**Comment by o-smirnov** [comment]
Befoe you release, don't forget that my verbose debug stuff is still in the two cubical cabs, e.g. https://github.com/ratt-ru/Stimela/blob/master/stimela/cargo/cab/cubical_ddf/src/run.py#L9

I am somewhat minded to make this a general Stimela "feature" though, at least in -debug mode.

**Pull request merged**
