### PR TITLE
Fix dtype of cubical BBC gains

### PR DESCRIPTION
**Pull request by bennahugo**

### CODE REVIEW

**Comment by o-smirnov** [comment]
I note this is also going on with all the other ``save-to`` options... maybe they all need this fix?

**Comment by bennahugo** [comment]
Not spotting which you are referring to?

**Comment by o-smirnov** [comment]
https://github.com/ratt-ru/Stimela/blob/master/stimela/cargo/cab/cubical/parameters.json, just search for "save-to".

**Comment by bennahugo** [comment]
Remaining dtypes are all of type file as far as I can tell

**Pull request merged**
