### PR TITLE
Cubical model api

### PR DESCRIPTION
**Pull request by SpheMakh**
Here is an example:

```python
 "model-list": ["MODEL_DATA", "MODEL_POINTS"],
 "model-expr": ["0-1", "1"],
 "out-subtract-dirs": 1,
```

### CODE REVIEW

**Review by JSKenyon — COMMENTED** [review]
I am not against this API but I do think it is worth mentioning that the Stimela API will now differ wildly from the CubiCal API. This is not a crisis but it does mean that Stimela needs to document how its arguments map to the CubiCal arguments, as CubiCal's docs definitely won't be of much use. You have effectively created a new recipe syntax. Out of interest, how are you handling tags on input sky models/dico models for degridding?

**Comment by o-smirnov** [comment]
Meet the new syntax, better than the old syntax!

I agree we need a clearly documented mapping between the two, otherwise native users of CubiCal will have unprintable things to say about us when they transition to the Stimela version (or vice versa). 

If it is truly better syntax, we could also consider reincorporating it into CubiCal itself?

We also need to have a good think about how to redo this in QuartiCal. A structured yaml-based config, rather than a flat list, would be a lot kinder on the user, and would be mappable 1:1 to Stimela syntax.

**Comment by SpheMakh** [comment]
> We also need to have a good think about how to redo this in QuartiCal. A structured yaml-based config, rather than a flat list, would be a lot kinder on the user, and would be mappable 1:1 to Stimela syntax.

Agreed

**Comment by JSKenyon** [comment]
We did discuss this at length at one point in the past. Currently, QuartiCal uses CubiCal's model specification because... I have actually forgotten but I seem to recall that splitting into multiple arguments felt error-prone. My worry was that users would have to correctly specify multiple arguments as well as "index-by-eye" the model inputs. Perhaps making the indexes explicit like: 
```
"model-list": ["MODEL_DATA", "MODEL_POINTS"],
"model-indices": ["d0", "d1"] 
"model-expr": ["d0-d1", "d1"],
 "out-subtract-dirs": 1,
```

**Comment by SpheMakh** [comment]
Yes, having explicit labels would make it more transparent.

**Comment by o-smirnov** [comment]
Think bolder, free your keys:
```yml
model:
  components:
    a: MODEL_DATA
    b: MODEL_POINTS
    c: data.lsm.html
  dirs: 
    x: a-b
    y: b
    z: c
out:
  subtract:
    dirs: [y, z]
```
And for the user who likes to be terse, one could easily support both lists and dicts:
```yml
model:
  components: MODEL_DATA, MODEL_POINTS, data.lsm.html
  dirs: 0-1,1,2
out:
  subtract: 
    dirs: 2,3
```

**Comment by JSKenyon** [comment]
That is fine in the yaml, where this is easy. What does the command line look like in that case?

**Comment by o-smirnov** [comment]
I got @SpheMakh to buy into OmegaConf because the dotted key thing solves these problems in one stroke:

 ``model.components=MODEL_DATA,MODEL_POINTS,data.lsm.html model.dirs=0-1,1,2 out.subtract.dirs=2,3``

**Comment by JSKenyon** [comment]
I was more intrigued by the first case. But I will get to OmegaConf - just have other, more critical fires at present.

**Comment by o-smirnov** [comment]
I suspect that ``model.components={a:MODEL_DATA,b:MODEL_POINTS,c:data.lsm.html}`` will work. Modulo a few quotes and here there.

**Pull request closed without merging**
