### PR TITLE
Add breizorro

### PR DESCRIPTION
**Pull request by Athanaseus**
A tool for creating a binary mask given a FITS image

### CODE REVIEW

**Comment by Athanaseus** [comment]
ok to test

**Comment by Athanaseus** [comment]
restest this please

**Comment by Athanaseus** [comment]
retest this please

**Comment by Athanaseus** [comment]
retest this please

**Review by SpheMakh — APPROVED** [review]
Looks good

**Comment by SpheMakh** [comment]
Done

**Comment by Athanaseus** [comment]
retest this please

**Pull request merged**
