### PR TITLE
Aimfast3 updates

### PR DESCRIPTION
**Pull request by Athanaseus**

### CODE REVIEW

**Comment by SpheMakh** [comment]
@Athanaseus do you know why the test failed?

**Comment by Athanaseus** [comment]
Not really sure if it relates to changes in this PR, but here is the traceback from Jenkins:

```
======================================================================
ERROR: testEndToEndReduction (stimela-test-meerkat.mk_reduce)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/PR_stimela/workspace/237/projects/Stimela/stimela/tests/acceptance_tests/stimela-test-meerkat.py", line 235, in testEndToEndReduction
    recipe.run()
  File "/var/lib/jenkins/jobs/PR_stimela/workspace/237/projects/pyenv/lib/python3.6/site-packages/stimela/recipe.py", line 764, in run
    raise PipelineException(exc, self.completed, job, self.remaining) from None
stimela.exceptions.PipelineException: Job 'image2' failed: docker returns error code 137

----------------------------------------------------------------------
Ran 13 tests in 7156.336s

FAILED (errors=1)
```

**Comment by Athanaseus** [comment]
ok to test

**Comment by Athanaseus** [comment]
retest this please

**Comment by Athanaseus** [comment]
@SpheMakh if you approve this I can merge.

**Review by SpheMakh — APPROVED** [review]

**Pull request merged**
