### PR TITLE
fixes #606

### LINKED ISSUE #606: singularity imports ${HOME} inside the container and causes version clashes
This is again broken in singularity. Singularity ignores paths set up in the docker container so scipy has to be removed from the base
```
#   File "/usr/local/lib/python3.6/dist-packages/cubical/degridder/DicoSourceProvider.py", line 3, in <module>
#     from DDFacet.Imager import ModModelMachine as MMM
#   File "/usr/local/lib/python3.6/dist-packages/DDFacet/__init__.py", line 23, in <module>
#     __version__ = pkg_resources.require("DDFacet")[0].version
#   File "/home/hugo/vmk_test/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
#     needed = self.resolve(parse_requirements(requirements))
#   File "/home/hugo/vmk_test/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
#     raise VersionConflict(dist, req).with_context(dependent_req)
# pkg_resources.ContextualVersionConflict: (scipy 1.4.1 (/home/hugo/vmk_test/venv3/lib/python3.6/site-packages), Requirement.parse('scipy<=1.3.3'), {'DDFacet'})
```

### PR DESCRIPTION
**Pull request by bennahugo**
@SpheMakh @o-smirnov  this is a workaround for 606. unfortunately it also limits shared memory to 50%, but I guess we have to live with that. Hopefully this will go away as soon as we can move to version 2.

The issue was indeed the import of the environment variables and the virtual environment into the container, because singularity imports the entire home folder.

### CODE REVIEW

**Comment by bennahugo** [comment]
ok but can we please merge this because your previous push broke my pipeline. This is not related to @KshitijT's problem

**Comment by bennahugo** [comment]
This runs through for me now using singularity.

**Comment by bennahugo** [comment]
I now have an end to end test from 1GC through to 3GC selfcal using my pipeline that I will put onto Jenkins. You will be glad to know that everything now works, including the CASA plotms tasks and gain plotting

**Comment by o-smirnov** [comment]
Excellent!

So my push to cubical master (sorry @JSKenyon, a slip of the finger!) should fix @KshitijT's problem.

But should we be running all singularity images with --contain, or just this one? As I suggested elsewhere, maybe you should consider adding optional "docker_options" and "singularity_options" entry to ``parameters.json``, which, for this particular image only, will contain ``--contain``.

Also please pass in the ``USER`` environment variable.

**Comment by bennahugo** [comment]
All singularity images should be run with --contain because this in my opinion is a deficiency that will continue rearing its head with python installations.

**Comment by bennahugo** [comment]
so can we merge this please. The uid fixes can be done in a separate PR

**Comment by SpheMakh** [comment]
But why merge something that we know is not working?

**Comment by bennahugo** [comment]
but this is working

**Comment by bennahugo** [comment]
I've tested it this morning

**Comment by SpheMakh** [comment]
@KshitijT ran this earlier with `--containall` it failed with UID not found error

**Comment by SpheMakh** [comment]
Also, how do you build these ddfacet/cubical images?

```
  Stored in directory: /root/.cache/pip/wheels/e8/41/75/b739a7849d59e9af194414414726bb0e5cde129322e89d3655
  Building wheel for ddfacet (PEP 517): started
  Building wheel for ddfacet (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpz2xukixs
       cwd: /tmp/pip-install-sq65oq26/ddfacet
  Complete output (99 lines):
  running bdist_wheel
  running build
  -- The C compiler identification is GNU 7.5.0
  -- The CXX compiler identification is GNU 7.5.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Invalid option for BUILD TYPE, defaulted to 'Release' build
  -ffast-math is enabled
  -- Debug CXXFLAGS are -g -fopenmp -std=c++14 -Wall -fmax-errors=1 -ggdb3 -pedantic -W -Wall -Wconversion -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
  -- Release CXXFLAGS are -O3 -DNDEBUG -fopenmp -std=c++14 -ggdb3 -fmax-errors=1 -pedantic -W -Wall -Wconversion -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION    -ffast-math
  -- Compiling backend against Python 3.x
  -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3.0")
  -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable version "3.6.9", minimum required is "3.6")
  -- Found NumPy: /usr/local/lib/python3.6/dist-packages/numpy/core/include
  -- Found OpenMP_C: -fopenmp (found version "4.5")
  -- Found OpenMP_CXX: -fopenmp (found version "4.5")
  -- Found OpenMP: TRUE (found version "4.5")
  -- Found components for RT
  -- RT_INCLUDES = /usr/include
  -- RT_LIBRARIES = /usr/lib/x86_64-linux-gnu/librt.so
  -- Found Pybind11: /usr/local/include/python3.6;/root/.local/include/python3.6m
  -- Configuring done
  CMake Error at Gridder/CMakeLists.txt:85 (add_library):
    Cannot find source file:
  
      Arrays.cc
  
    Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
    .hxx .in .txx
  Call Stack (most recent call first):
    Gridder/CMakeLists.txt:101 (build_be)
  
  
  CMake Error at Gridder/CMakeLists.txt:90 (add_library):
    Cannot find source file:
  
      GridderSmearPols.cc
  
    Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
    .hxx .in .txx
  Call Stack (most recent call first):
    Gridder/CMakeLists.txt:101 (build_be)
  
  
  CMake Error: CMake can not determine linker language for target: _pyArrays3x
  CMake Error: Cannot determine link language for target "_pyArrays3x".
  CMake Error: CMake can not determine linker language for target: _pyGridderSmearPols3x
  CMake Error: Cannot determine link language for target "_pyGridderSmearPols3x".
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-sq65oq26/ddfacet/DDFacet/cbuild
  Compiling extension libraries with user defined options: '-DENABLE_NATIVE_TUNING=OFF -DENABLE_FAST_MATH=ON -DCMAKE_BUILD_TYPE=ReleaseWithDebugSymbols'
  Traceback (most recent call last):
    File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py", line 205, in build_wheel
      metadata_directory)
    File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 213, in build_wheel
      wheel_directory, config_settings)
    File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 198, in _build_with_temp_dir
      self.run_setup()
    File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 250, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 143, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 183, in <module>
      'fits-beam-support': ['meqtrees-cattery'],
    File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "setup.py", line 91, in run
      backend(self.compopts)
    File "setup.py", line 68, in backend
      (path, compile_options if compile_options is not None else ""), ""], shell=True)
    File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cd DDFacet/cbuild && cmake -DENABLE_NATIVE_TUNING=OFF -DENABLE_FAST_MATH=ON -DCMAKE_BUILD_TYPE=ReleaseWithDebugSymbols -DENABLE_PYTHON_2=OFF  -DENABLE_PYTHON_3=ON  .. && make', '']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for ddfacet

```

**Comment by bennahugo** [comment]
Well then we need to stop using singularity because we cannot have it mount the home folder. I have no idea how to fix this if --containall doesn't work. @o-smirnov can you please install docker on the Rhodes cluster? With no public facing boxes there should be no risk.

**Comment by bennahugo** [comment]
@SpheMakh using my dockerfile

**Comment by SpheMakh** [comment]
I only changed the repo branch

```
FROM stimela/ddfacet:1.3.3
MAINTAINER <sphemakh@gmail.com>
ENV GIT_LFS_SKIP_SMUDGE 1
RUN pip3 install -U pip setuptools wheel
RUN apt-get update && apt-get install -y wget git-all
RUN git clone -b decasacore300fication https://github.com/ratt-ru/CubiCal
WORKDIR CubiCal
#RUN git checkout decasacore300fication
RUN pip3 install -I ".[lsm-support,degridder-support]"
RUN DDF.py --help
RUN gocubical --help
ENV NUMBA_CACHE_DIR /tmp
ENTRYPOINT []
```

**Comment by bennahugo** [comment]
Things like lofarsoft and meqtrees has no pypi wheels so it has to be done by hand

**Comment by bennahugo** [comment]
Don't try to rebuild ddfacet or force an upgrade. You need the latest GCC to build ddfacet

**Comment by o-smirnov** [comment]
I don't understand why it's triggering a build of the ddfacet wheel, but that's the thing that needs to be avoided.

**Comment by bennahugo** [comment]
Also why are we installing a branch? This is how things cannot be rebuild in the future. Can we please stick to releases? The release before the busy week works

**Comment by bennahugo** [comment]
This line is the problem: ```RUN pip3 install -I ".[lsm-support,degridder-support]"``` this should be specified without the -U flag in the installation step of cubical to avoid upgrading ddfacet

**Comment by o-smirnov** [comment]
> Also why are we installing a branch? 

Because we are experimenting whether this will solve the problem.

**Comment by o-smirnov** [comment]
(@KshitijT's problem, that is...)

**Comment by bennahugo** [comment]
Ok what I'm going to do is fork stimela and develop on a separate fork based off a commit prior to the recent massive overhaul of stimela. I really need to finish my PhD reductions within the next two months to keep on track to finish my writeup this year. I've already lost another week because these issues.

**Comment by o-smirnov** [comment]
But why @bennahugo, I thought you just said earlier you had a working end-to-end run?

There was always going to be frenetic code churn because of the CARACal release, but now that the worst is over, it seems especially counterproductive to fork...

**Comment by o-smirnov** [comment]
IMHO the right approach is to get to the bottom of this Singularity problem and not just jump at any hack that seems to work. Now that R1 Caracal is out everyone can relax, take a deep breath and solve the problem properly.

**Comment by bennahugo** [comment]
The fix works for me so I'm going to use it for now. as I said I can't afford to wait on the reductions.

**Comment by o-smirnov** [comment]
Yeah sure @bennahugo, if it works, run with whatever works for you for now. This is an infrastructural issue, either the pipeline runs or it crashes (as opposed to something that e.g. changes the way the science images look, which is not the problem here thank god!), so at least it's easy to verify any given fix!

I'm just saying, now that caracal is out, and your pipeline works, we can all chill out a little and look at the singularity issues with a fresh eye, without the rush to release. Get a proper fix in place, give it a proper test with both your pipelines and caracal, then do a point release of stimela... then we shouldn't need to fork anything...

**Comment by bennahugo** [comment]
I've just tested this again and it runs through completely. I'm not sure what @KshitijT is doing but there is no problem if you mount an empty home folder and specify containall. Also the quoted error is running in docker, not singularity, so it seems to be unrelated
```
2020-05-12 00:55:01 STIMELA.backup_1GC_flags_0 INFO: job complete at 2020-05-12 00:55:01.561322 after 0:00:07.847523
2020-05-12 00:55:01 STIMELA.MeerKAT: INTROSPECT selfcal pipeline INFO: Saving pipeline information in .last_MeerKAT__INTROSPECT_selfcal_pipeline.json
2020-05-12 00:55:01 STIMELA.MeerKAT: INTROSPECT selfcal pipeline INFO: Recipe executed successfully
.
----------------------------------------------------------------------
Ran 3 tests in 14466.640s

OK
```

**Comment by bennahugo** [comment]
@SpheMakh can you please test this from your end. It is not necessary to alter anything in the ddfacet image - it works perfectly and it doesn't address the core of the problem. The problem with the way singularity mounts and we need to find a solution for that, otherwise we will continue running into this issue.

**Comment by o-smirnov** [comment]
I agree, let's please identify the core problem precisely. At the moment this is like software development by lobbing grenades at a house of cards in a dark room, and hoping the explosion is just right to correct the tilting east wing.

If ``--containall`` is the solution, then I for one would like to understand **exactly** what the problem is. Down to the nuts and bolts. Which part of the host environment messages with the container, and where? And why did ``--containall`` break other images in the pipeline (which at some point yesterday it did...)?

**Comment by o-smirnov** [comment]
> And why did --containall break other images in the pipeline (which at some point yesterday it did...)?

Or maybe it didn't, I think we have some confusion about this. OK, let's spend some time today clearing this up.

**Comment by bennahugo** [comment]
The problem is as follows;
 1. singularity ignores environment variables set inside the docker image. Which I fixed by moving things around in the base ddf docker image of stimela. That works now
 2. singularity imports ${HOME} as is
 3. singularity imports environment variables from the host

This results in a clash if there is any imported libraries in the PATH or VIRTUALENV of the host. So the solution is the --contain flag which will make a virtual home with nothing in it at container runtime.

@SpheMakh reports he still runs into issues elsewhere, but I can't help if I don't have backtraces.

**Comment by bennahugo** [comment]
The backtrace above is not singularity btw.

**Comment by o-smirnov** [comment]
Thanks @bennahugo, that makes it a lot clearer. I don't quite understand how any virtualenv leaks through. Or is it because PATH is passed through, and so the ``venv/bin/python3`` binary is actually invoked **inside** the container?

**Comment by bennahugo** [comment]
That is correct

**Comment by SpheMakh** [comment]
@bennahugo `--containall` should definitely be enabled as that avoids host settings from contaminating the container. The change you propose is part of the `cubical_ddf` branch which works even on 2.4.2-dist. 

I'm closing this one because the changes are already covered.

**Comment by bennahugo** [comment]
Could we please remove cubical_ddf. It works as is and should be build this way. I explicitly build in support for all sorts of extra functionality in ddfacet and I don't make 5 different cabs for it

**Comment by SpheMakh** [comment]
Sorry, I didn't realise you also had poltsiakat bug fixes in this PR also. Please resolve conflicts and retest.

**Comment by o-smirnov** [comment]
So are you saying there should be one all-conquering ddfacet image or one cubical image?

**Comment by SpheMakh** [comment]
The current setup is good. We have ddfacet, cubical and cubical_ddf images, the user can decide which combo is best for them.

**Comment by SpheMakh** [comment]
Conflicts resolved

**Pull request merged**
