### PR TITLE
Issue 687

### LINKED ISSUE #670: provide cabs for RM synth tools
@francescaLoi can advise which, I believe she mentioned ``pyrmsynth`` and ``RM-tools``.

### PR DESCRIPTION
**Pull request by SpheMakh**
inherited from #670 so also Fixes #670

### CODE REVIEW

**Comment by SpheMakh** [comment]
@bennahugo @o-smirnov it seems docker is down on jenkins

**Comment by SpheMakh** [comment]
retest this please

**Comment by SpheMakh** [comment]
retest this please

**Comment by SpheMakh** [comment]
retest this please

**Comment by SpheMakh** [comment]
retest this please

**Comment by SpheMakh** [comment]
retest this please

**Comment by SpheMakh** [comment]
retest this please

**Comment by SpheMakh** [comment]
pinging @o-smirnov

**Review by o-smirnov — APPROVED** [review]

**Pull request merged**
