### PR TITLE
UPdate base to use kern-6 and update pybdsf

### LINKED ISSUE #675: PyBDSM takes forever (or hangs) inside Stimela container
Got the following simple recipe courtesy of @Athanaseus:
```!python
import stimela
import sys

INPUT = '.'
OUTPUT = '.'
MSDIR = 'msdir'

IMAGE = sys.argv[1]
PIX_THRESH = int(sys.argv[2])
ISL_THRESH = int(sys.argv[3])


stimela.register_globals()

recipe = stimela.Recipe('Source Finder', ms_dir=MSDIR)
#JOB_TYPE='singularity', singularity_image_dir=os.environ["STIMELA_PULLFOLDER"])


recipe.add('cab/pybdsm', 'source_finder',
        {
            "filename"        :   "{}:output".format(IMAGE),
            "outfile"            :   "pybdsm_{}".format(IMAGE[:-5]),
            "thresh_pix"     :    PIX_THRESH,
            "thresh_isl"      :    ISL_THRESH,
            "clobber"          :    True,
            "catalog_type" :    "gaul",
            "group_tol"    : 12,
            "adaptive_rms_box" : True
        },
            input=INPUT,
            output=OUTPUT,
            label='src_finder:: Sourcery')

recipe.run()
```
Funning it in ``/net/young//home/oms/projects/OldDevils/selfcal-4C12.03/test`` with ``1558752655-MFS-image.fits`` and thesholds of 50, 30, the thing loops forever late in the Gaussian fitting stage:
```
# Fitting islands with Gaussians .......... : [-] 357/390
```
There's one CPU core using 100%. Some of these runs eventually succeed (after e.g. 18 hours!!)

Running the same job natively in the KERN version of pybdsf, with the same options, the job finishes in <10mins. Curiously though, it only fits 319 Gaussians.

So I assume there's something different in the Stimela defaults compared to the normal PyBDSM defaults. But what? And if so, this is misleading and should be fixed.

### PR DESCRIPTION
**Pull request by Athanaseus**
resolves #675

### CODE REVIEW

**Comment by o-smirnov** [comment]
I'll slap a DON'T MERGE label on it just for the moment, because switching **everything** over to KERN-6 seems like at least a minor (second-digit) release so maybe a bit more choreography is needed.

Should we do a 1.6.8 release with #678 #680 #682 merged, then release Caracal 1.0.4, then do Stimela 1.7.0 with this PR?

**Comment by KshitijT** [comment]
> Should we do a 1.6.8 release with #678 #680 #682 merged, then release Caracal 1.0.4, then do Stimela 1.7.0 with this PR?

Please, let's do that, that way we can include @Mulan-94 's PR in Caracal 1.0.4 too.

**Comment by o-smirnov** [comment]
Which @Mulan-94 PR is this?

**Comment by KshitijT** [comment]
> Which @Mulan-94 PR is this?

https://github.com/caracal-pipeline/caracal/pull/1249.  Relies on #680 .

**Comment by o-smirnov** [comment]
Ah yes, hence my concern here: https://github.com/ratt-ru/Stimela/pull/680#issuecomment-712872837

**Comment by KshitijT** [comment]
> Ah yes, hence my concern here: [#680 (comment)](https://github.com/ratt-ru/Stimela/pull/680#issuecomment-712872837)

Yes, from what I see, @Mulan-94 has removed `gaintype` from ragavi invocations in CARACal, but it's a chicken-and-egg problem, as in we need new stimela to confirm CARACal runs fine with #680 ( and because I am too lazy to change stimela back-and-forth while testing multiple CARACal PRs).

**Comment by o-smirnov** [comment]
> but it's a chicken-and-egg problem

Yers, which is why I made suggestions on #680 which should get around this, hopefully straight to the mammalian stage.

**Pull request closed without merging**
