### PR TITLE
updated BDSM

### PR DESCRIPTION
**Pull request by o-smirnov**

### CODE REVIEW

**Comment by o-smirnov** [comment]
This is a smaller update than #676 (as it doesn't update the base image), so can be done in a point release before #676 is merged.

If #676 goes in first, however, then this one is redudndant.

**Comment by SpheMakh** [comment]
@o-smirnov can you please push the image to the online repo 

`quay.io/stimela/pybdsf:1.6.0`

**Review by SpheMakh — CHANGES_REQUESTED** [review]
base image is not online `quay.io/stimela/pybdsf:1.6.0`

**Comment by SpheMakh** [comment]
retest this please

**Review by SpheMakh — APPROVED** [review]
Fixed

**Pull request merged**
