### PR TITLE
Jason's LogMustFall

### PR DESCRIPTION
**Pull request by o-smirnov**

### CODE REVIEW

**Comment by o-smirnov** [comment]
restest this please

**Comment by o-smirnov** [comment]
retest this please

**Comment by o-smirnov** [comment]
retest this please

**Comment by o-smirnov** [comment]
retest this please

**Review by bennahugo — APPROVED** [review]

**Comment by bennahugo** [comment]
As discussed this should be parsed out of docker ps and podman ps. I'm not sure if it can be done with singularity though. Will need to check into it

**Comment by o-smirnov** [comment]
I dunno if ``stimela ps`` is even useful at the moment, since it no longer runs (or leaves behind) containers in the background. There's a running instance of Stimela, and if it is interrupted, it stops all of its containers neatly. 

For ``stimela images`` etc., I have a better solution in mind using labels etc. See discussion here: https://github.com/ratt-ru/Stimela/issues/652. Labels are supported by all container technologies it seems.

**Pull request merged**
